#!/usr/bin/env bash
# LoanBuddy workshop bootstrap: everything that is NOT an AgentCore primitive.
# Idempotent - safe to re-run.
set -euo pipefail

STACK="${STACK:-loanbuddy-workshop}"
PREFIX="${PREFIX:-loanbuddy}"
REGION="${AWS_REGION:-us-east-1}"
PROFILE_ARG=()
[[ -n "${AWS_PROFILE:-}" ]] && PROFILE_ARG=(--profile "$AWS_PROFILE")

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ALICE_PASSWORD="LoanBuddy-alice-2026!"
BOB_PASSWORD="LoanBuddy-bob-2026!"

say() { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }

# ---------------------------------------------------------------------------
say "Deploying CloudFormation stack: $STACK ($REGION)"
aws cloudformation deploy "${PROFILE_ARG[@]}" --region "$REGION" \
  --stack-name "$STACK" \
  --template-file "$ROOT/infra/template.yaml" \
  --parameter-overrides "ResourcePrefix=$PREFIX" \
  --capabilities CAPABILITY_NAMED_IAM \
  --no-fail-on-empty-changeset

out() {
  aws cloudformation describe-stacks "${PROFILE_ARG[@]}" --region "$REGION" \
    --stack-name "$STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

USER_POOL_ID=$(out UserPoolId)
SPA_CLIENT_ID=$(out SpaClientId)
M2M_CLIENT_ID=$(out M2MClientId)
DOCS_BUCKET=$(out DocsBucket)
UI_BUCKET=$(out UiBucket)
UI_URL=$(out UiUrl)
REGISTRY_URL=$(out RegistryUrl)
DISCOVERY_URL=$(out CognitoDiscoveryUrl)
TOKEN_ENDPOINT=$(out CognitoTokenEndpoint)
GATEWAY_SCOPE=$(out GatewayScope)
EXPERIAN_URL=$(out ExperianApiUrl)
TABLE=$(out LoanApplicationsTable)

# ---------------------------------------------------------------------------
say "Seeding Cognito users (alice, bob)"
for u in alice bob; do
  pass_var="$(echo "$u" | tr '[:lower:]' '[:upper:]')_PASSWORD"
  aws cognito-idp admin-create-user "${PROFILE_ARG[@]}" --region "$REGION" \
    --user-pool-id "$USER_POOL_ID" --username "$u" \
    --message-action SUPPRESS >/dev/null 2>&1 || true   # exists on re-run
  aws cognito-idp admin-set-user-password "${PROFILE_ARG[@]}" --region "$REGION" \
    --user-pool-id "$USER_POOL_ID" --username "$u" \
    --password "${!pass_var}" --permanent
done

# ---------------------------------------------------------------------------
say "Generating sample documents (fresh dates) and staging to S3"
PYBIN="$ROOT/.venv/bin/python"; [[ -x "$PYBIN" ]] || PYBIN=python3
"$PYBIN" -c "import PIL" 2>/dev/null || "$PYBIN" -m pip install -q "Pillow>=12.1.1,<13"
"$PYBIN" "$ROOT/infra/seed/generate_docs.py" "$ROOT/infra/seed/sample-docs"
aws s3 sync "${PROFILE_ARG[@]}" --region "$REGION" --quiet \
  "$ROOT/infra/seed/sample-docs" "s3://$DOCS_BUCKET/sample-docs/"

# ---------------------------------------------------------------------------
say "Publishing UI and mock registry"
ACCOUNT_ID=$(aws sts get-caller-identity "${PROFILE_ARG[@]}" --query Account --output text)
sed -e "s|REPLACED_BY_BOOTSTRAP_REGION|$REGION|" \
    -e "s|\"us-east-1\"|\"$REGION\"|" \
    -e "s|REPLACED_BY_BOOTSTRAP_BADGE|account $ACCOUNT_ID|" \
    -e "s|userPoolId: \"REPLACED_BY_BOOTSTRAP\"|userPoolId: \"$USER_POOL_ID\"|" \
    -e "s|spaClientId: \"REPLACED_BY_BOOTSTRAP\"|spaClientId: \"$SPA_CLIENT_ID\"|" \
    "$ROOT/ui/config.js" > /tmp/loanbuddy-config.js
aws s3 cp "${PROFILE_ARG[@]}" --region "$REGION" --quiet /tmp/loanbuddy-config.js "s3://$UI_BUCKET/config.js"
aws s3 cp "${PROFILE_ARG[@]}" --region "$REGION" --quiet "$ROOT/ui/index.html" "s3://$UI_BUCKET/index.html"
aws s3 cp "${PROFILE_ARG[@]}" --region "$REGION" --quiet "$ROOT/ui/app.js" "s3://$UI_BUCKET/app.js"
aws s3 cp "${PROFILE_ARG[@]}" --region "$REGION" --quiet "$ROOT/ui/styles.css" "s3://$UI_BUCKET/styles.css"
aws s3 cp "${PROFILE_ARG[@]}" --region "$REGION" --quiet \
  "$ROOT/infra/seed/registry-site/index.html" "s3://$UI_BUCKET/registry/index.html"

# ---------------------------------------------------------------------------
say "Writing workshop-env.sh (source this in every lab terminal)"
ENVFILE="$ROOT/workshop-env.sh"
cat > "$ENVFILE" <<EOF
# LoanBuddy workshop environment - generated by bootstrap.sh
# Usage:  source workshop-env.sh
export WORKSHOP_ROOT="$ROOT"
export AWS_REGION="$REGION"
export STACK="$STACK"
export AGENTCORE_SUPPRESS_RECOMMENDATION=1
export USER_POOL_ID="$USER_POOL_ID"
export SPA_CLIENT_ID="$SPA_CLIENT_ID"
export M2M_CLIENT_ID="$M2M_CLIENT_ID"
export DISCOVERY_URL="$DISCOVERY_URL"
export TOKEN_ENDPOINT="$TOKEN_ENDPOINT"
export GATEWAY_SCOPE="$GATEWAY_SCOPE"
export TABLE="$TABLE"
export DOCS_BUCKET="$DOCS_BUCKET"
export UI_URL="$UI_URL"
export REGISTRY_URL="$REGISTRY_URL"
export EXPERIAN_URL="$EXPERIAN_URL"
export SUPERVISOR_ROLE="$(out SupervisorRoleArn)"
export DOC_COORDINATOR_ROLE="$(out DocCoordinatorRoleArn)"
export CREDIT_ANALYST_ROLE="$(out CreditAnalystRoleArn)"
# helper used by the lab guides to read any stack output by name
out() {
  aws cloudformation describe-stacks --stack-name "\$STACK" \\
    --query "Stacks[0].Outputs[?OutputKey=='\$1'].OutputValue" --output text
}
EOF
[[ -n "${AWS_PROFILE:-}" ]] && echo "export AWS_PROFILE=\"$AWS_PROFILE\"" >> "$ENVFILE"

CARD="$ROOT/workshop-card.txt"
cat > "$CARD" <<EOF
============================================================
 LoanBuddy Workshop Card        ($(date))
============================================================
 Region              $REGION
 UI                  $UI_URL
 Mock registry       $REGISTRY_URL

 Login: alice        $ALICE_PASSWORD
 Login: bob          $BOB_PASSWORD

 Cognito user pool   $USER_POOL_ID
 SPA client id       $SPA_CLIENT_ID
 M2M client id       $M2M_CLIENT_ID
 Discovery URL       $DISCOVERY_URL
 Token endpoint      $TOKEN_ENDPOINT
 Gateway scope       $GATEWAY_SCOPE

 DDB ledger table    $TABLE
 Docs bucket         $DOCS_BUCKET
 Sample docs         s3://$DOCS_BUCKET/sample-docs/
 Experian mock API   $EXPERIAN_URL
 Experian API key    workshop-experian-key-2026

 Execution roles
   supervisor        $(out SupervisorRoleArn)
   doc-coordinator   $(out DocCoordinatorRoleArn)
   credit-analyst    $(out CreditAnalystRoleArn)
============================================================
EOF
say "Done. Your workshop card:"
cat "$CARD"
echo
echo "Next: run 'source workshop-env.sh' in every lab terminal you open."
