#!/usr/bin/env bash
# Generate workshop-env.sh and workshop-card.txt from the CloudFormation
# stack outputs. Called by bootstrap.sh; ALSO run directly by attendees at
# AWS-hosted events (where the stack was pre-deployed and seeded for you):
#
#   ./scripts/make-env.sh
#   source workshop-env.sh
set -eo pipefail

STACK="${STACK:-loanbuddy-workshop}"
REGION="${AWS_REGION:-us-east-1}"
PROFILE_ARG=()
[[ -n "${AWS_PROFILE:-}" ]] && PROFILE_ARG=(--profile "$AWS_PROFILE")
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

out() {
  aws cloudformation describe-stacks "${PROFILE_ARG[@]}" --region "$REGION" \
    --stack-name "$STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

USER_POOL_ID=$(out UserPoolId)
SPA_CLIENT_ID=$(out SpaClientId)
M2M_CLIENT_ID=$(out M2MClientId)
DISCOVERY_URL=$(out CognitoDiscoveryUrl)
TOKEN_ENDPOINT=$(out CognitoTokenEndpoint)
GATEWAY_SCOPE=$(out GatewayScope)
TABLE=$(out LoanApplicationsTable)
DOCS_BUCKET=$(out DocsBucket)
UI_URL=$(out UiUrl)
REGISTRY_URL=$(out RegistryUrl)
EXPERIAN_URL=$(out ExperianApiUrl)
ALICE_PASSWORD=$(out AlicePassword)
BOB_PASSWORD=$(out BobPassword)

ENVFILE="$ROOT/workshop-env.sh"
cat > "$ENVFILE" <<EOF
# LoanBuddy workshop environment - generated by make-env.sh
# Usage:  source workshop-env.sh
export WORKSHOP_ROOT="$ROOT"
export AWS_REGION="$REGION"
export STACK="$STACK"
export AGENTCORE_SUPPRESS_RECOMMENDATION=1
export USER_POOL_ID="$USER_POOL_ID"
export SPA_CLIENT_ID="$SPA_CLIENT_ID"
export M2M_CLIENT_ID="$M2M_CLIENT_ID"
export DISCOVERY_URL="$DISCOVERY_URL"
export TOKEN_ENDPOINT="$TOKEN_ENDPOINT"
export GATEWAY_SCOPE="$GATEWAY_SCOPE"
export TABLE="$TABLE"
export DOCS_BUCKET="$DOCS_BUCKET"
export UI_URL="$UI_URL"
export REGISTRY_URL="$REGISTRY_URL"
export EXPERIAN_URL="$EXPERIAN_URL"
export SUPERVISOR_ROLE="$(out SupervisorRoleArn)"
export DOC_COORDINATOR_ROLE="$(out DocCoordinatorRoleArn)"
export CREDIT_ANALYST_ROLE="$(out CreditAnalystRoleArn)"
# helper used by the lab guides to read any stack output by name
out() {
  aws cloudformation describe-stacks --stack-name "\$STACK" \\
    --query "Stacks[0].Outputs[?OutputKey=='\$1'].OutputValue" --output text
}
EOF
[[ -n "${AWS_PROFILE:-}" ]] && echo "export AWS_PROFILE=\"$AWS_PROFILE\"" >> "$ENVFILE"

CARD="$ROOT/workshop-card.txt"
cat > "$CARD" <<EOF
============================================================
 LoanBuddy Workshop Card        ($(date))
============================================================
 Region              $REGION
 UI                  $UI_URL
 Mock registry       $REGISTRY_URL

 Login: alice        $ALICE_PASSWORD
 Login: bob          $BOB_PASSWORD

 Cognito user pool   $USER_POOL_ID
 SPA client id       $SPA_CLIENT_ID
 M2M client id       $M2M_CLIENT_ID
 Discovery URL       $DISCOVERY_URL
 Token endpoint      $TOKEN_ENDPOINT
 Gateway scope       $GATEWAY_SCOPE

 DDB ledger table    $TABLE
 Docs bucket         $DOCS_BUCKET
 Sample docs         s3://$DOCS_BUCKET/sample-docs/
 Experian mock API   $EXPERIAN_URL
 Experian API key    workshop-experian-key-2026

 Execution roles
   supervisor        $(out SupervisorRoleArn)
   doc-coordinator   $(out DocCoordinatorRoleArn)
   credit-analyst    $(out CreditAnalystRoleArn)
============================================================
EOF

echo "Wrote $ENVFILE"
echo "Wrote $CARD"
echo "Next: source workshop-env.sh"
